### ISSUE TITLE
Make the SHAP-related functions flexible to use external models

### ISSUE THREAD

**Issue by LLeiSong** [LLeiSong/itsdm#4]
Now these SHAP-related functions take an internal defined function (`.pfun_shap`) to calculate Shapley values, so they can only be applied to the model created in package `itsdm`. These functions include: `variable_contrib`, `shap_dependence`, `variable_analysis`, and `spatial_response`. 

It will be more useful if they can take a user-customized predict function based on the user's own model that is created outside of `itsdm`. And this will be a long-lasting enhancement for the package. The issue will be opened and updated until the whole feature is ready to release.

**Comment by LLeiSong** [comment]
Not an easy enhancement because the functions are highly customized to the objects in this package. Will do it step by step if it is possible. One easy try is to provide a function to convert an external model to match with this package.

**Comment by ldemaz** [comment]
Could you make a generic function that works with predict objects from `biomod` as well as from `itsdm`?

**Comment by LLeiSong** [comment]
Surprisedly, it is almost done. Separate `shap_spatial_response` from `spatial_response`. And adapt other functions to use external models, except `variable_analysis`. But since Shapley values-based method is a post hoc method. The analysis can be done using `variable_contrib` and some extra work. Will update the vignettes to guide how to do so later.
