### ISSUE TITLE
Breaking change(s) in new version of fastshap

### ISSUE THREAD

**Issue by bgreenwell** [LLeiSong/itsdm#9]
Hi @LLeiSong, 

I am preparing a new release of [fastshap](https://github.com/bgreenwell/fastshap) for CRAN, and it seems like it will break some functionality in your package. You can see a list of changes [here](https://github.com/bgreenwell/fastshap/blob/master/NEWS.md). I suspect the biggest change affecting your package is that **fastshap** >= 0.1.0 will no longer return a tibble, but rather a matrix.

Just wanted to give you a heads up before I plan to submit in two weeks.

# itsdm

<details>

* Version: 0.2.0
* GitHub: https://github.com/LLeiSong/itsdm
* Source code: https://github.com/cran/itsdm
* Date/Publication: 2023-01-15 14:30:08 UTC
* Number of recursive dependencies: 85

Run `revdepcheck::revdep_details(, "itsdm")` for more info

</details>

## Newly broken

*   checking examples ... ERROR
    ```
    Running examples in ‘itsdm-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: detect_envi_change
    > ### Title: Detect areas influenced by a changing environment variable.
    > ### Aliases: detect_envi_change
    > 
    > ### ** Examples
    > 
    > # Using a pseudo presence-only occurrence dataset of
    ...
    +   variables = mod$variables,
    +   shap_nsim = 1,
    +   target_var = "bio1",
    +   var_future = 5)
    Just set the single future variable.
    Change current bio1 with 5.
    Error in UseMethod("pull") : 
      no applicable method for 'pull' applied to an object of class "c('explain', 'matrix', 'array')"
    Calls: detect_envi_change ... shap_dependence -> lapply -> FUN -> data.frame -> %>% -> pull
    Execution halted
    ```

**Comment by LLeiSong** [comment]
@bgreenwell Thank you so much for informing me! I will make the necessary adjustments to the code in accordance with your updates.
